### ISSUE TITLE
Autocomplete and comments

### ISSUE THREAD

**Issue by michaelewens** [kylebarron/language-stata#108]
More a feature request: turn-off auto-complete for comment lines.  Comments (mine at least) are rarely full of variable names or functions and thus do not benefit from the auto-complete popping up on nearly every word.   Great Atom package!

**Comment by kylebarron** [comment]
You can adjust this in the settings. Go to Settings > Autocomplete Plus and put
```
comment*
```
into the Scope Blacklist setting.

**Comment by kylebarron** [comment]
^
Settings > Packages > Autocomplete Plus

**Comment by michaelewens** [comment]
The solution is to add 

`.string, .comment`

 to the Scope Blacklist (see https://github.com/atom/autocomplete-plus/issues/1006)

**Comment by jfriend00** [comment]
I'm not sure why .string, .comment isn't a built-in default.  I almost gave up on Atom after 1/2 day with it because of the absolute pain from the auto-completion just trying to type comments in my code.  Then, eventually I did some googling and found several other reports of the same thing that were all closed for one reason or another, then finally found this one that offered a solution that works.  Why in the world would this not be the default setting and give people starting with Atom a much better experience?
