### ISSUE TITLE
Error detection for macros is strict about spaces

### ISSUE THREAD

**Issue by karldw** [kylebarron/language-stata#17]
language-stata flags it as an error to have macro assignment without spaces, even though it's valid stata code.  Would you consider changing the parser to not flag this as an error?

Here's a demo:
```stata
sysuse auto
sum price, detail

local x=r(p90)-r(p10)
local x= r(p90)-r(p10)
```

<img width="186" alt="stata_atom_issue" src="https://user-images.githubusercontent.com/12504708/30936444-bea7f782-a388-11e7-975a-0beac59bb950.png">

**Comment by kylebarron** [comment]
Thanks! I missed that bug since I always use a space before the =. 

It should be fixed with https://github.com/kylebarron/language-stata/commit/e41ebb39fd844b54d0368c10fab70381065c1e40. I pushed an update to Atom, so it should show up soon.

Let me know after you update if it still parses incorrectly.

**Comment by karldw** [comment]
Nope, it works perfectly!
