### ISSUE TITLE
Fix handling of escape character

### ISSUE THREAD

**Issue by bbdaniels** [kylebarron/language-stata#18]
Escaping local macro inside quotation marks breaks highlighter.

<img width="1088" alt="screenshot_2017-09-28_13_58_22" src="https://user-images.githubusercontent.com/1459122/30982301-fc564f62-a454-11e7-9c91-159cb4998cdc.png">

**Comment by kylebarron** [comment]
Thanks. 

I didn't know it was possible in Stata to escape a local by only escaping the _beginning_ tick, I thought you had to escape both the beginning and end ticks, like 
```
local strata "\`fakestrata\'"
```
Anyhow, I see it works both ways in Stata. I pushed a fix to Atom.
It now looks like this for me:

![image](https://user-images.githubusercontent.com/15164633/30983540-b7b7907e-a458-11e7-9da7-5efca8620877.png)

**Comment by bbdaniels** [comment]
Thanks very much! Yea the whole "Stata-quotes" syntax is insane and breaks everything, I never even thought of escaping both ticks 😂 plus it gives a constant stream of minor annoyances when you have both ` and ' as *different* automatic bracket-completion shortcuts.

**Comment by kylebarron** [comment]
When I had to escape ticks before, I just assumed that you would've had to escape both. I think in most languages, it would make you do that. 

You're right... I didn't actually realize before that there's no use in Stata for '...' to be used in valid syntax, since Stata doesn't accept single quotes as strings. 
I fixed that in version 0.5.23.
