### ISSUE TITLE
Program arguments not yellow after ///

### ISSUE THREAD

**Issue by peterhickmanj** [kylebarron/language-stata#19]
Sometimes people list arguments for a program after ///, which allows you to quickly explain the argument after the ///. The package does not highlight these arguments yellow.
![issue1](https://user-images.githubusercontent.com/10004003/31041853-1ee1c5d2-a56a-11e7-8c10-fa37e4305142.PNG)

**Comment by kylebarron** [comment]
This may be impossible to fix. The program applies tags to text inside the `syntax` command, but that's currently set as starting with `syntax` and ending with a newline. Ideally, to have this environment wrap over multiple lines, you'd want the environment to only end on a line that doesn't have a `///`. But to do that, I think you'd need something like `(?<!///[^\\n]+)\\n`, i.e. the environment wouldn't end if it saw `///` then any amount of text and then the end of the line.

However the [regex engine that Atom uses](https://github.com/geoffgarside/oniguruma/blob/master/Syntax.txt#L200) doesn't allow look-behinds to be of variable length. There's no way to do this without having a regex match of variable length, because I don't know how much text would occur after the `///`.

**Comment by kylebarron** [comment]
Success!

I realized that you could say begin with `syntax` and end with a newline `\n`, and then if you have comments inside that start with `///` and end with a newline `\n`, then any comment will 'push' the end of the environment to the next line!

I'm super happy I figured this out. This will go out in an update sometime today.

![image](https://user-images.githubusercontent.com/15164633/31409178-fe754e1e-add8-11e7-899c-73ddc32d1190.png)
