### ISSUE TITLE
Merge with `stata-language`?

### ISSUE THREAD

**Issue by nickeubank** [kylebarron/language-stata#5]
Hey @kylebarron seems like this package has gotten well ahead of our iffy support of stata-language. Happy to merge our repo into yours so there are no longer competing syntax packages (if that's possible? Not quite clear on how atom package manager handles that) or close and redirect it. 

cc: @benwhalley

**Comment by benwhalley** [comment]
Sounds like a good idea if this package has better support.

**Comment by nickeubank** [comment]
I admit I've been lax -- I'm more python than javascript, so have had trouble adding to the stata-language. Seems like @kylebarron has already worked in macros, more keywords, etc.

**Comment by kylebarron** [comment]
Test out this package on some code and let me know what you think before we merge the packages, just in case that's irreversible. 

I really like Atom, and I have to use Stata for most of my work, so I thought I'd improve Atom's Stata support. There are some really good language packages for Atom for other languages; I particularly like the language-python package, and that inspired my work on this. I'm especially happy that I got macro coloring and regular expression highlighting to work in Stata. If you haven't yet, check out the coloring in Atom for 
```stata
 di regexm("hello world", "wor[a-z]+$")
```

I have a couple things on my mind to do for this package:
- The language package gives a tag to each syntax element, and then it's up to the syntax theme to match colors to those tags. Different syntax themes may or may not use all the same name tags, so what's colored in one theme might not be colored in other themes. I developed this language package alongside the [Atom Material Syntax](https://github.com/atom-material/atom-material-syntax) theme, so when you use that theme, all elements of the package are in effect colorwise. However, a good language package should be portable to whatever theme the user chooses, so I need to go over the syntax tag names of some other main syntax themes to make sure that I've chosen appropriate names that all themes recognize.
- Along with this is the subtler point of choices of tag grouping. Right now, in the Material Syntax theme, locals and types are given the same orange color. So, for example, with the `syntax` command, this package colors everything after the `,` as orange (except the parentheses) because the `str` and `int` are types, and the `string_macro{1,2,3}` and `integer_macro` are in essence new macros. So, I need to figure out whether to change the tag names of macros and types if I decide I don't want them to be the same color. 
    ```stata
    syntax, string_macro1(str) integer_macro(int) string_macro2(str) string_macro3(str)
    ```
- There's a small fix I should do with the package's autocomplete settings to allow it to autocomplete all text instead of just macros and function names and command names.

The language packages aren't really written in Javascript; there's actually no javascript or even coffeescript in this package. Cson is just a clean way to store the language rules. I haven't checked the status of Stata syntax highlighting in Sublime Text, but it really wouldn't be difficult to port this package to Sublime; Sublime just uses [tags](https://github.com/andrewheiss/SublimeStataEnhanced/blob/master/Stata.tmLanguage) instead of explicit indentation. 

I have a wish list of future things to implement if I find time, like updating [docblockr](https://github.com/nikhilkalige/docblockr) to be able to parse the `syntax` command for easier documentation generation, but that does use javascript, which I don't know that well yet. Since I know Atom language package details pretty well right now, I'm also working on a better [language package for R](https://github.com/kylebarron/language-r), since the current one is unmaintained and has plenty of room for improvement (though R is a harder language to write good highlighting for).

**Comment by nickeubank** [comment]
@kylebarron You are a heck of a good citizen! 

I've been playing with your package today, and it think it pretty strictly dominates the other one. I think that one is basically a straight port from sublime text, and a lot of things failed to carry over in the transition. 

Regex colors are gorgeous!

Thanks also for the R package! Was disappointed to find that the package you forked off (what I had been using) is no longer supported. Like you, I much prefer Atom to Sublime (I'm increasingly working in Julia a lot, as well as python, and for those it crushes sublime), but need to use Stata and R with some frequency. 

Feel better to learn syntax isn't javascript or coffeescript -- don't feel so bad for finding syntax weird then. :)

**Comment by kylebarron** [comment]
Thanks!

Definitely create issues on here for any suggestions/issues you might have or find. I ported the simplified regex syntax from the python package, so that wasn't actually too difficult. 

My R packages is pretty broken right now. Definitely not ready for production use. The original maintainer of that R package no longer uses R, and the other people who've signed up as volunteer maintainers haven't really done anything. I'm hopeful that when my R update is finished, I can get the attention of one of those new maintainers and maybe get write access. 

I hope you're familiar with [Hydrogen](https://github.com/nteract/hydrogen) for use with Python, R, and Julia.

I might be able to go through some tag names tonight and then be ready to merge repos if you desired. I'm not sure how you want to do the merge.

**Comment by nickeubank** [comment]
If @benwhalley  is ok with it, I'm all for essentially overriding the existing repo with yours. Happy to follow your lead on what you think is easiest. 

Re: Hydrogen, nice! I've been using [Juno](http://junolab.org) for Julia. Will give Hydrogen a shot!

**Comment by kylebarron** [comment]
I made another small addition to the package but otherwise I'm happy to merge. I was reading a thread (https://github.com/atom/apm/issues/73) about renaming Atom packages. I tried `apm publish --rename language-stata` and it failed (as it should while your package still exists):
```bash
> apm publish --rename language-stata
Renaming language-stata-plus to language-stata ✓
Preparing and tagging a new version ✓
Pushing v0.5.4 tag ✓
Publishing language-stata@v0.5.4 ✗
Creating new version failed: A package by that name already exists
```
That makes it sound like one way to merge the packages is just for you to do `apm unpublish` and then for me to do `apm publish --rename language-stata`. That way your github repo would still exist. Granted, I'm not sure what this would do to people who currently have your `language-stata` installed.

**Comment by kylebarron** [comment]
I just tested this out:
I made a package `test-atom-package2`, published it to apm as that name, and installed it in Atom. I then made another package `test-atom-package3`, published that to apm, then unpublished `package2` and renamed `package3` as `package2`. It seemed that as long as the newer package has a higher version number than the old package, users will be prompted to install it as an update. (My `language-stata` has a higher version number than yours already, so that wouldn't be an issue).

Apm does tell you when you unpublish a package:
> Are you sure you want to unpublish ALL VERSIONS of 'test-atom-package2'? This will remove it from the apm registry, including download counts and stars, and this action is irreversible.

I just want to make sure you're ok with that.

**Comment by nickeubank** [comment]
OK -- @benwhalley think you need to -- I don't appear to a have authority. 

    ➜  ~ apm unpublish language-stata
    Are you sure you want to unpublish ALL VERSIONS of 'language-stata'? This will remove it from 
    the apm registry, including download counts and stars, and this action is irreversible. (no)yes
    Unpublishing language-stata ✗
    Unpublishing failed: Unauthorized

**Comment by benwhalley** [comment]
OK - all done! Thanks for all your help Nick.

**Comment by nickeubank** [comment]
You guys have done all the heavy lifting! Thanks for all your work on this

**Comment by kylebarron** [comment]
The rename was successful: https://atom.io/packages/language-stata.

Go to Settings > Updates > Check for Updates to see if you get a prompt to update your `language-stata` package.
