### ISSUE TITLE
Autocomplete single-quotes for local macros

### ISSUE THREAD

**Issue by nickeubank** [kylebarron/language-stata#6]
A long-standing request we never figured out how to implement...

https://github.com/benwhalley/atom-language-stata/issues/15

**Comment by kylebarron** [comment]
That's resolved with this [line of code](https://github.com/kylebarron/language-stata/blob/3c3e10149601faf19e2dfa81d64ff5820dc4abbb/settings/language-stata.cson#L10). 

Essentially, the package overrides the defaults in the bracket-matcher package.

**Comment by nickeubank** [comment]
@kylebarron great! is that in current release? Wasn't seeing it in own editor behavior

**Comment by kylebarron** [comment]
Hmm you're right.  It's working with `' in my own Atom setup, but when I installed the package in a Windows VM, it didn't autocomplete. I need to do a little more debugging.

**Comment by nickeubank** [comment]
FWIW I'm on a mac

**Comment by kylebarron** [comment]
I think it's due to the fact that this language package is changing settings for the bracket-matcher package that were already loaded before installing language-stata-plus. Those won't get reloaded for the Stata scope until you reload Atom. It doesn't seem to always work by just closing Atom and reopening it; Atom probably has some background process. 

Do cmd-shift-P to open up the command prompt and choose "Window: Reload" (ctrl+shift+F5 on Windows and Linux). The bracket matching should function properly after that reload.

**Comment by nickeubank** [comment]
yup. That was embarassing! :) Thanks!

**Comment by kylebarron** [comment]
It wasn't clear to me that I restart was needed. I'll add that to the README.
