### ISSUE TITLE
Better toggle comment block

### ISSUE THREAD

**Issue by andreamoro-git** [kylebarron/language-stata#85]
Hi Kyle,
would it be possible to enter a newline at the end of the comment block when toggling a comment block? It would make it a bit easier to spot comment block

Issue: currently, when edit/toggle comments selected rows it produces the following
```
/* reg y x z
reg y1 y1*/
```
I would prefer some of the following:
```
/* 
reg y x z
reg y1 y2 
*/
```
or, if you don't want to alter the line numbers:
```
* reg y x z
* reg y1 y2 
```

**Comment by kylebarron** [comment]
The `toggle-line-comments` function, which is run by <kbd>ctrl</kbd>-<kbd>/</kbd> is a core Atom function, not one that I specify in this package. The only option I have is to change the character that creates the comment block. 

I could change the comment character to `*`, which would change to the third option you posted, but that disrupts the following situation:
```
di 2 /// 
	* 3
```
The second line is valid Stata syntax, but if you run `toggle-line-comments` on the second line, instead of adding a `*`, it'll take the multiplication away, since it thinks it's a comment. Often style guides, like [Python's](http://pep8.org/#break-before-or-after-binary-operator), encourage keeping operators in line in this way. 

Your options are:
1. Select the empty lines before and after the chunk you want to comment, which will produce your second code chunk
2. Override the package and make `*` your comment character. You can do this by putting the following into your `config.cson`:
    ```
    '.source.stata':
      'editor':
        'commentStart': '* '
    ```

**Comment by andreamoro-git** [comment]
sounds good, thanks

**Comment by kylebarron** [comment]
I'm considering changing the default to `//` instead of `/* */`
